<div class="content post-detail"
     data-url="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
     data-title="<?php echo $this->arrContent['cont_title'] ?>" data-id="<?php echo $this->arrContent['cont_id'] ?>"
     data-load="true">
    <h1>
        <?php echo $this->arrContent['cont_title']; ?>
    </h1>
    <div class="socialbox top clearfix">
        <ul>
            <li class="raty" itemscope itemtype="http://data-vocabulary.org/Review-aggregate">
                <meta itemprop="itemreviewed" content="<?php echo $this->arrContent['cont_title']; ?>"/>
                <meta itemprop="rating" content="4"/>
                <meta itemprop="votes" content="14"/>
                <span class=" rating" data-rating="4" data-id="<?php echo $this->arrContent['cont_id']; ?>"></span>
                <span class="rating-info">4</span><span class="rating-votes">14</span>
            </li>
            <li class="views"><?php echo number_format($this->arrContent['cont_views'] + 1, 0, ",", "."); ?></li>
            <li class="share">
                <div class="sharebox">
                    <div class="sharetoolbox">
                        <!--                        <div class="g-plusone" data-annotation="none" data-size="medium" data-href="http://khoahoc.tv/3-bi-an-ve-trai-dat-chua-co-loi-giai-dap-40490"></div>-->

                        <!--                        <div class="fb-like" data-href="http://khoahoc.tv/3-bi-an-ve-trai-dat-chua-co-loi-giai-dap-40490" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>-->
                        <!--                        <div class="fb-like likebox" data-href="https://www.facebook.com/khoahoc.tivi" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>-->
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <div class="breadcrumbs info-detail" xmlns:v="http://rdf.data-vocabulary.org/#">
        <span class="first breadcrumb">
            <a href="<?php echo BASE_URL; ?>">🏠</a>
        </span>
        <?php if (!empty($this->arrCategoryParent)): ?>
            <span typeof="v:Breadcrumb" class="breadcrumb">
                    <a rel="v:url" property="v:title"
                       href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryParent['cate_slug'], 'cateId' => $this->arrCategoryParent['cate_id']]) ?>">
                        <?php echo $this->arrCategoryParent['cate_name']; ?>
                    </a>
                </span>
        <?php endif; ?>
        <span typeof="v:Breadcrumb" class="breadcrumb">
                    <a rel="v:url" property="v:title"
                       href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id']]) ?>">
                        <?php echo $this->arrCategoryDetail['cate_name']; ?>
                    </a>
                </span>
    </div>

    <div class="content-detail">
        <div id="adsarticletop" class="adbox">
            <!-- KhoaHoc - BaiViet - Reponsive -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-9275417305531302"
                 data-ad-slot="2384218482"
                 data-ad-format="auto"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
        <?php echo $this->arrContent['cont_detail']; ?>
        <script>
            //            if (location.hostname.toLowerCase().indexOf("khoahoc.tv") < 0) { location.href = "http://khoahoc.tv/"; }
        </script>
    </div>
    <div class="author-info clearfix">
        <span class="date">Cập nhật: <?php echo date('d/m/Y', $this->arrContent['updated_date']) ?></span>
        <span class="author" style="float: right">Tổng hợp</span>
    </div>

    <div class="tags">
        <span><b>Xem thêm:</b></span>
        <?php if (!empty($this->arrKeywordList)):
            foreach ($this->arrKeywordList as $arr_key):
                ?>
                <a href="<?php echo $this->serverUrl() . $this->Url('keyword', array('keySlug' => $arr_key['key_slug'], 'keyId' => $arr_key['key_id'])) ?>"><?php echo $arr_key['key_name']; ?></a>
                <?php
            endforeach;
        endif; ?>
    </div>

    <div class="listitems">
        <div class="title">Tham khảo thêm</div>
        <ul>
            <?php if (!empty($this->arrContentLikeList)):
                foreach ($this->arrContentLikeList as $arr_content):
                    ?>
                    <li>
                        <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>">
                            <?php echo $arr_content['cont_title']; ?>
                            <span><?php echo number_format($arr_content['cont_views'], 0, ",", "."); ?>
                                người xem</span>
                        </a>
                    </li>
                <?php endforeach;
            endif;
            ?>
        </ul>
    </div>

    <!--    <div id="adsarticlebottom" class="adbox">-->
    <!--        <!-- KhoaHoc-BaiViet-Resposive -->
    <!--        <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9275417305531302"-->
    <!--             data-ad-slot="8671917284" data-ad-format="auto"></ins>-->
    <!--        <script>-->
    <!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
    <!--        </script>-->
    <!--    </div>-->
    <div class="socialbox bottom clearfix">
        <ul>
            <li class="share">
                <div class="sharebox">
                    <div class="sharetoolbox">
                        <div class="g-plusone" data-annotation="none" data-size="medium"
                             data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"></div>

                        <div class="fb-like"
                             data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
                             data-layout="button_count" data-action="like" data-show-faces="false"
                             data-share="true"></div>
                    </div>
                </div>
            </li>
            <li class="raty">
                <span class="rating" data-rating="4" data-id="40490"></span>
                <span class="rating-info">4</span><span class="rating-votes">14</span>
            </li>
            <li class="views"><?php echo number_format($this->arrContent['cont_views'] + 1, 0, ",", "."); ?></li>
        </ul>
    </div>


    <!--    <p>-->
    <!--        <a href="https://www.facebook.com/khoahoc.tivi" target="_blank" rel="nofollow">Theo dõi cộng đồng KhoaHoc.tv trên-->
    <!--            facebook</a></p>-->
    <!--    <div class="fb-like" data-href="https://www.facebook.com/khoahoc.tivi" data-layout="standard"-->
    <!--         data-action="recommend" data-show-faces="true" data-share="true"></div>-->
    <!---->
    <!--    <div class="comments">-->
    <!--        <div id="fb_comments" class="fb-comments"-->
    <!--             data-href="http://khoahoc.tv/3-bi-an-ve-trai-dat-chua-co-loi-giai-dap-40490" data-num-posts="3"-->
    <!--             data-width="640"></div>-->
    <!--    </div>-->
    <!--    <div id="suggestion" class="adbox">-->
    <!--        <ins class="adsbygoogle" style="display: inline-block; width: 100%; height: 250px"-->
    <!--             data-ad-client="ca-pub-9275417305531302" data-ad-slot="6979590889"></ins>-->
    <!--        <script>-->
    <!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
    <!--        </script>-->
    <!--    </div>-->

    <div class="more-news latest">
        <div class="list-title">Bài viết mới nhất</div>
        <ul class="clearfix">
            <?php foreach ($this->arrContentNews as $arr_content): ?>
                <li>
                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>">
                        <span class="thumb-detail">
                            <img src="<?php echo $arr_content['cont_main_image'] ?>"
                                 alt="<?php echo $arr_content['cont_title'] ?>"/>
                        </span>
                        <span><?php echo $arr_content['cont_title'] ?></span>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
        <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryParent['cate_slug'], 'cateId' => $this->arrCategoryParent['cate_id']]) ?>"
           class="viewmore"><b>Xem thêm</b> <?php echo $this->arrCategoryParent['cate_name']; ?></a>
    </div>

    <div class="more-news">
        <div class="list-title">Bài viết <?php echo $this->arrCategoryDetail['cate_name']; ?> khác</div>
        <ul class="clearfix">
            <?php
            if (!empty($this->arrContentLastedList)):
                foreach ($this->arrContentLastedList as $arr_content):
                    ?>
                    <li>
                        <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>">
                        <span class="thumb-detail">
                            <img src="<?php echo $arr_content['cont_main_image'] ?>"
                                 alt="<?php echo $arr_content['cont_title'] ?>"/>
                        </span>
                            <span><?php echo $arr_content['cont_title'] ?></span>
                        </a>
                    </li>
                <?php endforeach;
            endif;
            ?>
        </ul>
        <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id']]) ?>"
           class="viewmore">Xem thêm</a>
    </div>
</div>
