<div class="content">
    <div class="slider">
        <ul>
            <li>
                <a href="muoi-co-thuc-su-lam-cho-nuoc-soi-nhanh-hon-binh-thuong-hay-khong-75509.html">
                    <img class="thumb"
                         src="<?php echo STATIC_URL; ?>/f/v1/photos/image/2016/09/26/cho-muoi-vao-noi-650-size-650x340-znd.jpg"
                         alt="Muối c&#243; thực sự l&#224;m cho nước s&#244;i nhanh hơn b&#236;nh thường hay kh&#244;ng?"/>
                    <span>Muối c&#243; thực sự l&#224;m cho nước s&#244;i nhanh hơn b&#236;nh thường hay kh&#244;ng?</span>
                </a>
            </li>
            <li>
                <a href="9-cau-hoi-thuong-gap-o-tre-em-va-cach-tra-loi-khoa-hoc-hop-ly-75498.html">
                    <img class="thumb"
                         src="<?php echo STATIC_URL; ?>/f/v1/photos/image/2016/09/26/nguoi-vo-gia-cu-650-size-650x340-znd.jpg"
                         alt="9 c&#226;u hỏi thường gặp ở trẻ em v&#224; c&#225;ch trả lời khoa học, hợp l&#253;"/>
                    <span>9 c&#226;u hỏi thường gặp ở trẻ em v&#224; c&#225;ch trả lời khoa học, hợp l&#253;</span>
                </a>
            </li>
            <li>
                <a href="dau-hieu-ve-su-song-dau-tien-tren-trai-dat-co-the-la-vi-khuan-75492.html">
                    <img class="thumb"
                         src="<?php echo STATIC_URL; ?>/f/v1/photos/image/2016/09/25/Dickinsonia-Costa-650-size-650x340-znd.jpg"
                         alt="Dấu hiệu về sự sống đầu ti&#234;n tr&#234;n Tr&#225;i Đất c&#243; thể l&#224; vi khuẩn"/>
                    <span>Dấu hiệu về sự sống đầu ti&#234;n tr&#234;n Tr&#225;i Đất c&#243; thể l&#224; vi khuẩn</span>
                </a>
            </li>
        </ul>
    </div>

    <div id="adindexcenter" class="adbox" style="margin-bottom:20px">
        <!-- KhoaHoc Cat Resp -->
        <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9275417305531302"
             data-ad-slot="3096293681" data-ad-format="auto"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
    <div class="listview">
        <ul>
            <?php
            foreach ($this->arrContentList as $arrContent):
                ?>
                <li class="listitem clearfix">
                    <a class="title"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]) ?>">
                        <?php echo $arrContent['cont_title']; ?>
                    </a>
                    <a class="thumb"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]) ?>">
                        <img src="<?php echo $arrContent['cont_main_image']; ?>"
                             alt="<?php echo $arrContent['cont_title']; ?>"/>
                    </a>
                    <div class="desc"><?php echo $arrContent['cont_description']; ?></div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="pagination-container">
        <ul class="pagination">
            <?php if ($this->intPage > 1):
                if ($this->intPage == 2):?>
                    <li class="PagedList-skipToPrevious">
                        <a href="<?php echo BASE_URL; ?>" rel="prev">Quay lại</a>
                    </li>
                <?php else: ?>
                    <li class="PagedList-skipToPrevious">
                        <a href="<?php echo BASE_URL; ?>/?page=<?php echo $this->intPage - 1; ?>" rel="prev">Quay
                            lại</a>
                    </li>
                <?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($this->arrContentList)): ?>
                <li class="PagedList-skipToNext">
                    <a href="<?php echo BASE_URL; ?>/?page=<?php echo $this->intPage + 1 ?>" rel="next">Xem thêm</a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
</div>