<div class="content">
<!--    <div class="slider">-->
<!--        <ul>-->
<!--            --><?php //foreach ($this->arrContentList as $key => $arrContent):
//                if ($key >= 3) {
//                    break;
//                }
//                ?>
<!--                <li>-->
<!--                    <a href="--><?php //echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]) ?><!--">-->
<!--                        <img class="thumb"-->
<!--                             src="--><?php //echo $arrContent['cont_main_image']; ?><!--"-->
<!--                             alt="--><?php //echo $arrContent['cont_title']; ?><!--"/>-->
<!--                        <span>--><?php //echo $arrContent['cont_title']; ?><!--</span>-->
<!--                    </a>-->
<!--                </li>-->
<!--            --><?php //endforeach; ?>
<!--        </ul>-->
<!--    </div>-->

    <div id="adindexcenter" class="adbox" style="margin-bottom:20px">
        <!-- khampha content -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:728px;height:90px"
             data-ad-client="ca-pub-4608570842050780"
             data-ad-slot="5752635152"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
    <div class="listview">
        <ul>
            <?php
            foreach ($this->arrContentList as $key => $arrContent):
                ?>
                <li class="listitem clearfix">
                    <a class="title"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]) ?>">
                        <?php echo $arrContent['cont_title']; ?>
                    </a>
                    <a class="thumb"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]) ?>">
                        <img src="<?php echo $arrContent['cont_main_image']; ?>"
                             alt="<?php echo $arrContent['cont_title']; ?>"/>
                    </a>
                    <div class="desc"><?php echo $arrContent['cont_description']; ?></div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="pagination-container">
        <ul class="pagination">
            <?php if ($this->intPage > 1):
                if ($this->intPage == 2):?>
                    <li class="PagedList-skipToPrevious">
                        <a href="<?php echo BASE_URL; ?>" rel="prev">Quay lại</a>
                    </li>
                <?php else: ?>
                    <li class="PagedList-skipToPrevious">
                        <a href="<?php echo BASE_URL; ?>/?page=<?php echo $this->intPage - 1; ?>" rel="prev">Quay
                            lại</a>
                    </li>
                <?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($this->arrContentList)): ?>
                <li class="PagedList-skipToNext">
                    <a href="<?php echo BASE_URL; ?>/?page=<?php echo $this->intPage + 1 ?>" rel="next">Xem thêm</a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
</div>