<div class="content">
    <h1 style="color : blue"><?php echo $this->arrKeyDetail['key_name'] ?></h1>
    <div class="taxdesc">
    </div>
    <div class="breadcrumbs info-detail" xmlns:v="http://rdf.data-vocabulary.org/#">
        <span class="first breadcrumb">
            <a href="<?php echo BASE_URL; ?>">🏠</a>
        </span>
        <span typeof="v:Breadcrumb" class="breadcrumb">
            <a rel="v:url" property="v:title"
               href="<?php echo $this->serverUrl() . $this->Url('keyword') ?>">
                Từ khóa
            </a>
        </span>
    </div>
<!--    <div id="adindexcenter" class="adbox" style="margin-bottom:20px">-->
<!--        <!-- khampha content -->
<!--        <ins class="adsbygoogle"-->
<!--             style="display:inline-block;width:728px;height:90px"-->
<!--             data-ad-client="ca-pub-4608570842050780"-->
<!--             data-ad-slot="5752635152"></ins>-->
<!--        <script>-->
<!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
<!--        </script>-->
<!--    </div>-->
    <?php if (!empty($this->arrContentList)): ?>
        <div class="listview">
            <ul>
                <?php foreach ($this->arrContentList as $arr_content): ?>
                    <li class="listitem clearfix">
                        <a class="title"
                           href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>">
                            <?php echo $arr_content['cont_title']; ?>
                        </a>
                        <a class="thumb"
                           href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>">
                            <img src="<?php echo $arr_content['cont_main_image'] ?>"
                                 alt="<?php echo $arr_content['cont_title'] ?>"/>
                        </a>
                        <div class="desc"><?php echo $arr_content['cont_description'] ?>
                        </div>
                    </li>
                <?php endforeach; ?>
                <!--        </ul>-->
                <!--    </div>-->
                <!--    <div id="adindexcenter" class="adbox" style="margin-bottom:20px">-->
                <!--        <!-- KhoaHoc Cat Resp -->
                <!--        <script>-->
                <!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
                <!--        </script>-->
                <!--    </div>-->
                <!--    <div class="listview">-->
                <!--        <ul>-->
            </ul>
        </div>
    <?php endif; ?>
<!--    <div id="adindexcenter" class="adbox" style="margin-bottom:20px">-->
<!--        <!-- khampha content -->
<!--        <ins class="adsbygoogle"-->
<!--             style="display:inline-block;width:728px;height:90px"-->
<!--             data-ad-client="ca-pub-4608570842050780"-->
<!--             data-ad-slot="5752635152"></ins>-->
<!--        <script>-->
<!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
<!--        </script>-->
<!--    </div>-->
    <div class="listitems">
        <div class="title">Từ khoá tương tự</div>
        <ul>
            <?php if (!empty($this->arrKeywordList)):
                foreach ($this->arrKeywordList as $arr_key):
                    ?>
                    <li>
                        <a href="<?php echo $this->serverUrl() . $this->Url('keyword', array('keySlug' => $arr_key['key_slug'], 'keyId' => $arr_key['key_id'])) ?>">
                            <?php echo $arr_key['key_name']; ?>
                        </a>
                    </li>
                <?php endforeach;
            endif;
            ?>
        </ul>
    </div>
    <?php echo $this->paging ?>
</div>