<?php
$paramsRouter = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParams();
$routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$controller = $paramsRouter['__CONTROLLER__'];
$action = $paramsRouter['action'];
?>
<header id="header" class="container">
    <div id="mast-head">
        <div id="logo">
            <a href="<?php echo $this->serverUrl() . $this->Url('home') ?>" title="<?php echo \My\General::SITE_AUTH?>" rel="home"><img src="<?php echo STATIC_URL ?>/f/v1/images/logo.png" alt="Magazine" /></a>
        </div>
    </div>


    <nav class="navbar navbar-inverse clearfix nobot">

        <a id="responsive-menu-button" href="#swipe-menu">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>		
        </a>	

        <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
        <div class="nav-collapse" id="swipe-menu-responsive">

            <ul class="nav">

                <li>
                    <span id="close-menu">
                        <a href="#" class="close-this-menu">Close</a>
                        <script type="text/javascript">
                            jQuery('a.sidr-class-close-this-menu').click(function () {
                                jQuery('div.sidr').css({
                                    'right': '-476px'
                                });
                                jQuery('body').css({
                                    'right': '0'
                                });
                            });
                        </script>
                    </span>
                </li>
                <li><a href="<?php echo $this->serverUrl() . $this->Url('home') ?>"><img src="<?php echo STATIC_URL ?>/f/v1/images/home.png" alt="Magazine"></a></li>
                <li class="dropdown"><a href="<?php echo $this->serverUrl() . $this->Url('home') ?>">Home</a>
                </li>
                <?php
                $arr_cate_parent = unserialize(ARR_CATEGORY_PARENT);
                $arr_cate_children = unserialize(ARR_CATEGORY_BY_PARENT);
                foreach ($arr_cate_parent as $cate_parent):
                    ?>
                    <li class="dropdown"><a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $cate_parent['cate_slug'], 'cateId' => $cate_parent['cate_id']]) ?>"><?php echo $cate_parent['cate_name']; ?></a>
                        <ul class="sub-menu">
                            <?php foreach ($arr_cate_children[$cate_parent['cate_id']] as $cate_child): ?>
                                <li><a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $cate_child['cate_slug'], 'cateId' => $cate_child['cate_id']]) ?>"><?php echo $cate_child['cate_name'] ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                <?php endforeach; ?>
                <li><a href="about.html">About</a></li>
            </ul>

        </div><!--/.nav-collapse -->

    </nav><!-- /.navbar -->

</header><!-- #masthead -->

<div id="headline" class="container">
    <div class="row-fluid">

        <?php
        $arr_top_4 = unserialize(ARR_TOP_4_YEAR);
        foreach ($arr_top_4 as $key => $content):
            if($key > 3){
                break;
            }
            ?>
            <div class="span3">
                <article class="post">
                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>" title="<?php echo $content['cont_title']; ?>" rel="bookmark">
                        <img style="width: 91px; height: 55px" src="<?php echo $content['cont_main_image']; ?>" class="thumb" alt="<?php echo $content['cont_title']; ?>" />
                    </a>
                    <div class="entry">
                        <h3><a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>" title="<?php echo $content['cont_title']; ?>" rel="bookmark"><?php echo strlen($content['cont_title']) < 50 ? $content['cont_title'] : substr($content['cont_title'], 0, 46) . '...'; ?></a></h3>
                        <p><?php echo date('d/m/Y', $content['created_date']); ?> </p>
                    </div>
                    <div class="clearfix"></div>
                </article>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<div id="intr" class="container">
    <div class="row-fluid">
        <div class="brnews span9">
            <h3>Mới cập nhật</h3>
            <ul id="scroller">
                <?php
                $arr_new_list = unserialize(ARR_NEWS_LIST);
                foreach ($arr_new_list as $content):
                    ?>
                    <li><p><a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>" title="<?php echo $content['cont_title']; ?>" rel="bookmark"><span class="title"><?php echo strlen($content['cont_title']) < 40 ? $content['cont_title'] : substr($content['cont_title'], 0, 36) . '...' ?></span> <?php echo strlen($content['cont_desciption']) < 50 ? $content['cont_desciption'] : substr($content['cont_desciption'], 0, 46) . '...' ?></a></p></li>
                <?php endforeach; ?>
            </ul>
        </div>

        <div class="search span3"><div class="offset1">
                <form method="get" id="searchform" action="<?php echo $this->serverUrl().$this->Url('search')?>">
                    <p><input name="keyword" type="text" value="Từ khóa ..." onfocus="if (this.value == 'Từ khóa ...') {
                                this.value = '';
                            }" onblur="if (this.value == '') {
                                        this.value = 'Search here...';
                                    }" name="s" id="s" />
                        <input type="submit" id="searchsubmit" value="Search" /></p>
                </form>
            </div></div>
    </div>
</div>