<?php
$paramsRouter = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParams();
$routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$controller = $paramsRouter['__CONTROLLER__'];
$action = $paramsRouter['action'];
?>
<div class="leftbar">
    <div  class="navbox clearfix">
        <div class="title">☰ Danh mục</div>
        <ul id="leftnav" class="navigation clearfix">
            <?php
                foreach (unserialize(ARR_CATEGORY_BY_PARENT) as $arr_category):
                    if(!empty($arr_category)):
                        foreach ($arr_category as $category):?>
                            <li class="l2 tax-<?php echo $category['cate_slug'];?>">
                                <a href="cong-nghe-moi.html">
                                    <img src="<?php echo STATIC_URL.$category['cate_img_url'];?>" />
                                    <?php echo $category['cate_name'];?>
                                </a>
                            </li>
                        <?php endforeach;
                    endif;
                endforeach;
            ?>
        </ul>
    </div>

</div>